# Generated by Django 6.1.1 on 2026-09-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_reviewed_at_transaction_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NPR', max_length=3),
        ),
    ]
