# Generated by Django 6.1.1 on 2026-09-22 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_convert_existing_currency_to_npr'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='refund_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_refund_request', to='transactions.transaction'),
        ),
    ]
